project:
  type: website

website:
  title: "Carson Atwood Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: CV.qmd
        text: CV
      - href: pictures.qmd
        text: Pictures

format:
  html:
    theme:
      - s
    css: styles.css
    toc: true

editor: visual

